version: "3.8"

services:
  gmeet-api:
    build: .
    container_name: gmeet-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./recordings:/app/recordings
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
    restart: unless-stopped
